spring.application.name=pcm-api
application.title=Project & Client Managenement API
application.version=0.1.1

--PARAMETROS PARA CONEXION A BASE DE DATOS POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pcm_db
spring.datasource.username=mi_usuario
spring.datasource.password=mi_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

